name: Update Free VPN Subscription
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and Merge Free VPNs
        run: |
          curl -s "https://githubusercontent.com" > source1.txt
          curl -s "https://githubusercontent.com" > source2.txt
          curl -s "https://githubusercontent.com" > source3.txt
          
          cat source1.txt source2.txt source3.txt | sort -u > my_sub.txt
          base64 -w 0 my_sub.txt > index.txt
          rm source1.txt source2.txt source3.txt my_sub.txt

      - name: Upload Finished Subscription File
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
